name: bluetooth
description: Bluetooth plugin for Flutter
version: 0.0.2
author:
  - Paul DeMarco <paulmdemarco@gmail.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/truongsinh/flutter_bluetooth

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: '^2.1.1'
  protobuf: '^0.13.4'

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  pedantic: ^1.7.0
  uuid_enhanced: ^3.0.2
  flutter_test:
    sdk: flutter
